# MTJ Build Properties
S60.includes=src\
,res\
,orig_res\

S60.excludes=orig_res/dummy.txt\

S40.includes=src\
,res\
,orig_res\

S40.excludes=orig_res/dummy.txt\

Minimum.includes=src\
,res\
,orig_res\

Minimum.excludes=orig_res/en_hit.wav\
,orig_res/door.wav\
,orig_res/close.wav\
,orig_res/buy.wav\
,orig_res/bell.wav\
,orig_res/accolade.wav\
,orig_res/inmate.png\
,orig_res/inmate2.png\
,orig_res/inmate3.png\
,orig_res/rumble.wav\
,orig_res/plip.wav\
,orig_res/pickup.wav\
,orig_res/open.wav\
,orig_res/lose.wav\
,orig_res/light.png\
,orig_res/throw.wav\
,orig_res/hp.wav\
,orig_res/dummy.txt\

